### ISSUE TITLE
2.x Import stuck in loop ?

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#237] opened 2017-01-22 20:22 UTC
Hi Oro Team,

When starting an import, and there is no rows being imported, the job seems to execute again and again every 6 minutes ....

![image](https://cloud.githubusercontent.com/assets/794449/22185588/9029d15e-e0b6-11e6-9a53-73758095e00d.png)

It also seems that the Export job never send the completion notification

Have a good day,
Samuel

**Comment by mkudelya** [comment] 2017-01-24 16:25
Hi @sadortun 

I think job starts again and again because import contains some errors. What kind of errors do you see when click on 'Error log' link ?

**Comment by sadortun** [comment] 2017-01-24 17:37
My csv was missing a required field.

**Comment by tumbochka** [comment] 2017-01-25 10:03
Hi @sadortun
The wokflow is:
1. You press 'Import' or 'Import validation' button.
2. A message with the import params is created and is sent to the message queue.
3. When it turn comes the message is processed by a consumer.
4. The consumer runs an import or an import validation processor.
5.1 If the message params are bad (for example the import filename is missing) the message is rejected and doesn't appear in the MessageQueue any more.
5.2 If an exception is thrown on the message processing the message is re-delivered to the queue after some delay (the default delay is 10 seconds).
5.3 If the message is processed ok you receive an email with the results. It doesn't matter if the import passed with error or without, the message is considered to be processed successfully and doesn't redeliver to the message queue.

As you receive emails the import and import validation messages seem to be processed successfully.  Also notice that if a message is redelivered the default delay is 10 seconds not 6 minutes.

The possible reasons of the issue:

1. The import and the import validation are running periodically for some reasons. 
2. An issue with the mail transport: some emails are re-sent.

**Comment by sadortun** [comment] 2017-01-25 10:07
@tumbochka  I agree with you that what you described is the expected workflow, but on 5.2, it seems that the file get processed again, even if its contain unrecoverable errors. In my case, the file contain only the `email` and `firstName` fields, and all the others fields were empty.

I did not try with other type of files yet.

**Comment by tumbochka** [comment] 2017-01-25 10:14
@sadortun Could you provide more detailed steps to reproduce, your config and, if possible, the file  you're trying to import? We will try to reproduce locally.

on 5.2 - what do you mean?

**Comment by sadortun** [comment] 2017-01-25 10:16
I'll give you more detail on my next import / export

*step 4.2 (sorry it's late!)

**Comment by mkudelya** [comment] 2017-01-25 10:39
Hi

I have tried import lead csv file without Lead Name and only one email has been sent to me (similar error), i was waiting to second email, but nothing. I suggest you run "app/console oro:message-queue:consume -vvv" and watch similar topic's which can be sent to consumer. If consumer doesn't retrieve anything, you have problem in other areas.

>'oro.message_queue.client.topic_name' => 'oro.importexport.import_http_preparing'

>'oro.message_queue.client.topic_name' => 'oro.importexport.import_http'

I'm on 2.0 branch.

**Comment by mkudelya** [comment] 2017-02-28 15:53
Hi @sadortun 

I am now closing this issue as, unfortunately, we have not received any feedback from you. Please, feel free to reopen it if you have any questions.

**Closed by mkudelya** 2017-02-28 15:53 UTC
Labels: question
