### ISSUE TITLE
Scheduled Task - oro:cron:email-body-sync

### ISSUE THREAD

**Issue by aconite33** [orocrm/crm#220] opened 2016-09-22 19:58 UTC
Running version 1.10 on ubuntu 16.04, using Apache.
We're using Google integration in order to use email syncs.

Got it working fine, however when this scheduled task comes up this seems to hang the system and email sync will no longer work. Requires me to kill the oro:cron:imap-sync and the oro:cron:email-body-sync processes.

Once this is killed, everything returns to normal.

**Comment by aconite33** [comment] 2016-09-22 20:02
Here is a screen shot, showing that email-body-sync blocking other processes that need to be ran.
<img width="1477" alt="screen shot 2016-09-22 at 4 01 42 pm" src="https://cloud.githubusercontent.com/assets/3675886/18764075/f313b156-80dd-11e6-834f-4f716726932f.png">

**Comment by aconite33** [comment] 2016-09-29 00:43
I believe I found at least where this is occurring. It's in the EmailBodySynchronizer.php file, the "loadbody" function. Catching a general exception, line 95. (Modified the sprintf to figure out which exception was throwing). Seems to continue to run and never exits cleanly.

**Comment by artml** [comment] 2016-10-18 08:36
@aconite33 have you found a fix? Would be nice to know if your investigation was fruitful.

And thank you for reporting the issue, we will work on the fix.

**Comment by nzidol** [comment] 2016-11-17 21:04
Likely related issue "Load email body failed. Email id: 1293. Error: An exception occurred while executing 'INSERT INTO oro_email_attachment_content (content, content_transfer_encoding, attachment_id) VALUES (?, ?, ?)' with params ["UEsDBBQABgAIAAAAIQCj77sdZQEAAFIFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC (...)" which leaves the job running and blocking all other jobs.
![image](https://cloud.githubusercontent.com/assets/13618973/20407423/3a343320-ad76-11e6-9d5d-f342bda4eef7.png)

**Comment by nzidol** [comment] 2016-11-17 21:41
Looks like loadBody() re-throws the exception (line 238) which is not handled in syncOneEmailBody (line 77)
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/EmailBundle/Sync/EmailBodySynchronizer.php

**Comment by nzidol** [comment] 2016-11-17 22:02
Assume it will then be caught at line 134, but then line 86 was bypassed and setBodySynced is not set...?

**Comment by artml** [comment] 2016-12-02 17:59
@nzidol thanks for the info. The bug is still open, but we're committed to fix it in 2.0 (or at least in one of 2.0.x maintenance releases).

**Comment by nzidol** [comment] 2016-12-07 22:08
Part of the problem was that max attachment size was set differently in Oro and Nginx....

**Comment by mkudelya** [comment] 2017-02-07 15:27
@aconite33 
We can't reproduce issue with empty body on 1.10.14 and 2.0 versions of orocrm. Still you have the issue ?

@nzidol 

Can you show to me more detailed error with attachment ? How i can reproduce it ?

**Comment by aconite33** [comment] 2017-02-16 18:45
We have since moved on from this product and are no longer using it.

**Comment by mkudelya** [comment] 2017-04-14 09:16
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.

**Closed by mkudelya** 2017-04-14 09:16 UTC
Labels: bug, feedback needed
