### ISSUE TITLE
Task information dialog doesnt display html 

### ISSUE THREAD

**Issue by sadortun** [orocrm/crm#187] opened 2016-06-30 02:26 UTC
Hi Oro Team!

A quick one, In calandar, when clicking on a task, 

![image](https://cloud.githubusercontent.com/assets/794449/16474914/82a31d3a-3e48-11e6-87ad-24b37ea64764.png)
1. The Html is not rendered
2. Name escaping issue with `'`

Have a good day!

**Comment by startupz** [comment] 2016-06-30 06:09
+1

It would be a good feature

**Comment by artml** [comment] 2016-06-30 14:16
@sadortun isn't it the same as #174?

**Comment by sadortun** [comment] 2016-06-30 16:03
For (1),  No, it's a different dialog
For (2), Yes, it's similar issue , but it's two different dialogs, #187 is the  task popup on the calandar, and #174 is the "normal" task view page.

Also, to be noted, in the Task information dialog, doesn't have a clikable link on the name compared to the

**Comment by artml** [comment] 2016-06-30 16:23
Okay, thank you for clarification Samuel. We will work on a fix, but it remains to be seen if we will have time to do it within 1.10.0 release.

**Comment by Grygir** [comment] 2017-03-15 15:55
The issue is finally fixed and the fix will be available within upcoming release.

**Comment by mkudelya** [comment] 2017-04-26 16:37
As i can see, the issue has been fixed in version 2.1.
I am now closing this issue. Please, feel free to reopen it if you have any questions.

**Closed by mkudelya** 2017-04-26 16:37 UTC
Labels: bug, open for contribution

**Comment by sadortun** [comment] 2017-04-26 16:44
Awesome ! Thanks !
