### ISSUE TITLE
Add Task/Log Call/ Add Event windows popup upon login

### ISSUE THREAD

**Issue by devadathtabeti** [orocrm/crm#230] opened 2016-12-14 15:18 UTC
Hi, 

We are experiencing an issue , Where a user after working on Add Task / Log Call / Add Event . 
After logging off and logging back in , all these come back as new windows, though the user has saved those activities.

The state of those windows is maintained in the oro_windows_state table in the mysql database, which gets populated with rows when windows are opened and the rows are deleted automatically by orocrm once the windows are closed. 

Could you please help us analyse this issue further and resolve? 

Thanks
Devadath

**Comment by mkudelya** [comment] 2016-12-16 13:12
Hi

I can't reproduce your case. Which version of orocrm are you using ? What i did:

- login
- go to Contact view page
- add note, log call, add task
- logout
- login
- go to Contact view page

I'm using 1.10.12 version.

**Comment by devadathtabeti** [comment] 2016-12-16 14:15
Hi , 

Thanks for investigating. We found the cause of the issue. The autocommit on mysql db was switched off because of a locking issue and this caused the add task, log call or add note windows to be kept open even after saving. Once you logout and log back in , it would open as many windows as the tasks or log call or add note that were added by that user. 

Thanks and Regards

**Comment by mkudelya** [comment] 2017-02-28 14:50
Hi @devadathtabeti 

Sounds great! In this case I am now closing the issue.
Thank you for using OroCRM!

**Closed by mkudelya** 2017-02-28 14:50 UTC
Labels: issue fixed, question
