### ISSUE TITLE
Failed migrations: Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_2\OroOrganizationBundle

### ISSUE THREAD

**Issue by winzou** [orocrm/crm#143] opened 2015-12-15 07:02 UTC
Hi,

I was upgrading from v1.2 to v1.8.1, a lot of migrations are OK but it fails on this one:

     Failed migrations: Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_2\OroOrganizationBundle.

Link to the file on github: https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/OrganizationBundle/Migrations/Schema/v1_2/OroOrganizationBundle.php

Even with the option `-vvv` I have no clue at all on the issue. Did someone already got this issue? How can I move forward on this? The application is not working anymore of course...

Thanks!

**Comment by yurio** [comment] 2015-12-15 10:42
Hi, @winzou.
At the list of migrations, near Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_2\OroOrganizationBundle string where is real exception. 
Please copy it here.

**Comment by winzou** [comment] 2015-12-15 12:44
Hi @yurio, here is my full output of the command:

     $ php app/console oro:platform:update --force -vvv

    [...]

	  > OroCRM\Bundle\ActivityContactBundle\Migration\ActivityContactMigration - skipped
	  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
	  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped


																					
	  [RuntimeException]                                                            
	  Failed migrations: Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_2\OroOrganizationBundle.
																					


	oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>





	  [RuntimeException]
	  The command terminated with an exit code: 1.



	Exception trace:
	 () at /home/alex/crm.caissin.fr/current/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:200
	 Oro\Bundle\InstallerBundle\CommandExecutor->processResult() at /home/alex/crm.caissin.fr/current/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:143
	 Oro\Bundle\InstallerBundle\CommandExecutor->runCommand() at /home/alex/crm.caissin.fr/current/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/PlatformUpdateCommand.php:54
	 Oro\Bundle\InstallerBundle\Command\PlatformUpdateCommand->execute() at /home/alex/crm.caissin.fr/current/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
	 Symfony\Component\Console\Command\Command->run() at /home/alex/crm.caissin.fr/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
	 Symfony\Component\Console\Application->doRunCommand() at /home/alex/crm.caissin.fr/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
	 Symfony\Component\Console\Application->doRun() at /home/alex/crm.caissin.fr/current/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
	 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/alex/crm.caissin.fr/current/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:45
	 JMS\JobQueueBundle\Console\Application->doRun() at /home/alex/crm.caissin.fr/current/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
	 Symfony\Component\Console\Application->run() at /home/alex/crm.caissin.fr/current/app/console:23


	oro:platform:update [--force] [--symlink] [--force-debug] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--jms-job-id JMS-JOB-ID] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>

As you can see, there is absolutely no information for me to debug further :-/

**Comment by yurio** [comment] 2015-12-15 14:40
@winzou, thanks for the output. But, can you send code that you are skip with [...] ?
At this block, near the 
```
> Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_2\OroOrganizationBundle
```
string where is real exception. 

Thanks

**Comment by winzou** [comment] 2015-12-15 14:52
No there is no "real exception", What I skip in the `[...]` is all the previous migrations that were skipped (because I already executed the command, this sounds quite normal to me?). I kept only the last 3 in my previous comment.

**Comment by yurio** [comment] 2015-12-15 15:11
@winzou, if the migration have 'skipped' string, this means what some migration before this migration was crashed.
Migrations what already executed does not shows at this list.
And near the first 'skipped' migration where is information, why previous migration was crashed. That is why i asked you to send this log.

**Comment by winzou** [comment] 2015-12-28 11:16
OK I got it thanks, this "skipped" is not clear. Here is the first error that occurs:

    Process migrations...
    Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
    Oro\Bundle\EmailBundle\Migrations\Schema\v1_12\RemoveOldSchema
    ERROR: There is no table with name 'caissin_orocrm.oro_email_user' in the schema.

If I try to fix this one, I encounter more in the following migrations.

I am upgrading from v1.2 to v1.8.1.

**Comment by nenadalm** [comment] 2016-01-15 09:10
Hi, @winzou.

I tried to replicate your issue using following script:
```shell
#!/usr/bin/env bash

# $ php -v
# PHP 5.4.42 (cli) (built: Jun 22 2015 21:53:08) 
# Copyright (c) 1997-2014 The PHP Group
# Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
#     with Xdebug v2.2.4, Copyright (c) 2002-2014, by Derick Rethans

set -eu

git clone https://github.com/orocrm/crm-application.git crm-app-test
cd crm-app-test

# install v1.2
git reset --hard 1.2.0
perl -p -i -e 's/Component_Zend(.*\.git)/zend-\L\1/g' composer.lock # fix broken vendors
composer install --no-dev
./app/console oro:install --company-short-name "Comp" --company-name "Company" --user-name "user" --user-firstname "first" --user-lastname "last" --user-password "user" --force --timeout 3600 --sample-data y --user-email "user@example.com" --timeout 3600

# upgrade to v1.8
git reset --hard 1.8.1
composer install --no-dev
rm -rf app/cache/* web/js/* web/css/*
./app/console oro:platform:update --force --timeout 3600
```
here is output of the script:
[upgrade.zip](https://github.com/orocrm/crm/files/91538/upgrade.zip)

as you can see, I have problem with fixtures, but migrations went ok.

Based on information from you
> Process migrations...
Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
Oro\Bundle\EmailBundle\Migrations\Schema\v1_12\RemoveOldSchema
ERROR: There is no table with name 'caissin_orocrm.oro_email_user' in the schema.

order of migrations from my log
> ...
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_12\OroEmailBundle
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_12\RemoveOldSchema
...

and code of the migrations (in order it was executed):
https://github.com/orocrm/platform/blob/1.8.1/src/Oro/Bundle/EmailBundle/Migrations/Schema/v1_12/OroEmailBundle.php#L61
https://github.com/orocrm/platform/blob/1.8.1/src/Oro/Bundle/EmailBundle/Migrations/Schema/v1_12/RemoveOldSchema.php#L54

my guess is that something happened here:
https://github.com/orocrm/platform/blob/1.8.1/src/Oro/Bundle/EmailBundle/Migrations/Schema/v1_12/OroEmailBundle.php#L27

so that the migration didn't finish (but was marked as executed anyway) and on your following attempts to do the upgrade, next migration was run (RemoveOldSchema) but since the previous didn't create the table - it failed.

Is there any chance you could restore backup with 1.2 version, try to run the upgrade again and post output of the upgrade here? (first attempt to run the command - so I can see first error which occured)

it would be nice to receive full output this time.
(base on your system, you might run the command as
```
$ php app/console oro:platform:update --force | tee upgrade.log
``` 
and upload it here)

the problem will might be one of these:
https://github.com/orocrm/platform/blob/1.8.1/src/Oro/Bundle/EmailBundle/Migrations/Schema/v1_12/OroEmailBundle.php#L44
https://github.com/orocrm/platform/blob/1.8.1/src/Oro/Bundle/EmailBundle/Migrations/Schema/v1_12/OroEmailBundle.php#L51
(so either constraint with the same name already exists or the column doesn't have unique data)

**Comment by artml** [comment] 2016-06-14 17:45
@winzou do you still experience this issue?

**Closed** 2016-07-26 17:14 UTC
Labels: feedback needed

**Comment by josephdpurcell** [comment] 2017-02-23 18:04
I ran into this issue, or a similar issue. I received:

```
Setting up database.
Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
  > Oro\Bundle\UserBundle\Migrations\Schema\OroUserBundleInstaller
    ERROR: The target-entity OroEntityProxy\OroEmailBundle\EmailAddressProxy cannot be found in 'Oro\Bundle\EmailBundle\Entity\EmailRecipient#emailAddress'.
...
  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration - skipped

                                                                                      
  [RuntimeException]                                                                  
  Failed migrations: Oro\Bundle\UserBundle\Migrations\Schema\OroUserBundleInstaller.  
```


Here is what I did to resolve, but this is a DESTRUCTIVE path, so don't do it unless you can blow away the install:

1. Delete the database
1. cd .. && rm -rf orocommerce-application
1. git clone --recursive https://github.com/orocommerce/orocommerce-application.git
1. cd orocommerce-application && composer install --prefer-dist
1. php app/console oro:install --env=prod

No errors occurred after following the above. I assume the root of the problem is some state isn't getting handled properly on install failure.

**Comment by mkudelya** [comment] 2017-02-24 12:17
Hi @josephdpurcell 

Do you get this error after you've updated OroCommerce? Could you please tell me which version you upgraded from and to ?

**Comment by josephdpurcell** [comment] 2017-02-24 12:59
@mkudelya I received this error on a fresh install yesterday. On a high level, what happened was I git cloned and installed, ran into errors, deleted the app and database, repeat. So, this wasn't on an upgrade it was during a fresh install.

I have the output I can share after I check it for any details.

**Comment by josephdpurcell** [comment] 2017-02-24 14:35
I created a pastebin here, at the very end I switch from installing via CLI to the web app, right where I install tidy: http://pastebin.com/6WVqdPbm

**Comment by mkudelya** [comment] 2017-03-09 13:59
Hi @josephdpurcell 

Thank you for reporting the issue.

I was able to reproduce it. You can avoid errors, if you remove app/cache/[dev&prod] folders once you have fixed this error: `[Doctrine\DBAL\Exception\DriverException] An exception occured in driver: could not find driver`.
