### ISSUE TITLE
Ststem email setup error "At least one folder for sent emails is required."

### ISSUE THREAD

**Issue by sparkind** [orocrm/crm#248] opened 2017-02-07 01:20 UTC
While setting up a system email box, imap and smtp. After clicking "Check connection/Retrieve Folders" and selecting a folder (all, inbox, ect tried everything) I still get the error message 

"At least one folder for sent emails is required. Make sure you clicked button "Check connection/Retrieve folders" and there are some folders for incoming messages."

I cannot seem to get past this glitch.  Setting up user emails with the same email server has no issues.

**Comment by RocKordier** [comment] 2017-02-07 08:49
Hey @sparkind,
have a look into the [Storage/Folder](https://github.com/orocrm/platform/blob/1.10.15/src/Oro/Bundle/ImapBundle/Mail/Storage/Folder.php#L9) class (1.10.15). Did you have a folder named 'Sent', 'SentBox' ... in your mail account?
I think ATM it's not possible to configure this values. We had the same problem in one of our projects so we have extended the class like this because we are not able to create folders in every account: 
```
<?php

namespace ACME\Bundle\OroImapBundle\Mail\Storage;

use Zend\Mail\Storage\Folder as BaseFolder;

/**
 * Class Folder
 *
 * @package ACME\Bundle\Mail\Storage
 */
class Folder extends \Oro\Bundle\ImapBundle\Mail\Storage\Folder
{
    public function __construct($localName, $globalName, $selectable)
    {
        parent::__construct($localName, $globalName, $selectable);
        $this->possibleSentFolderNameMap = [
            'SentBox',
            'Sent',
            'NewSentFolderName',
            'AnotherNewSentFolderName',
        ];
    }
}
```

In Oro 2.0.0. there is a [property](https://github.com/orocrm/platform/blob/2.0.0/src/Oro/Bundle/ImapBundle/Mail/Storage/Folder.php#L9) `$knownFolderNameMap` which can  be extended in the same way.

Hope that helps.
Eric

**Comment by sparkind** [comment] 2017-02-09 19:23
Note yet, still having issues with this and upgrading the system

On Feb 9, 2017, at 11:13 AM, Mykhailo Kudelia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sparkind<https://github.com/sparkind>

Please tell me, did you resolve your problem?

**Comment by mkudelya** [comment] 2017-02-09 20:31
Which problems do you have with upgrading ?

**Comment by thetailor** [comment] 2017-02-13 14:56
Hi @mkudelya,
as I said on slack, I'm having the same issue when I try to add a System Mailbox.

OroCRM (1.10.16)
My folder structure is:
All
- Inbox
- - Drafts
- - Sent
- - Templates
- - Trash
- - Spambucket

The system return always (if I choose only Inbox and Sent folders or all folders.) error "At least one folder for sent emails is required. Make sure you clicked button "Check connection/Retrieve folders" and there are some folders for incoming messages."

**Comment by sparkind** [comment] 2017-02-16 21:55
I upgraded everything to 2.0.1 and even tried a different mail provider and I still get "At least one folder for sent emails is required. Make sure you clicked button "Check connection/Retrieve folders" and there are some folders for incoming messages." no matter what is clicked.

**Comment by sparkind** [comment] 2017-02-17 19:45
I tried a personal gmail account as a test and ORO accepted it without a problem. However it still did not dispatch a password reset email when requested. I believe there is something not set correctly with our email email provider (rackspace).

**Comment by mkudelya** [comment] 2017-02-23 11:54
Hi @sparkind 

Could you please show me your folder structure, just like @thetailor did it? If the structure is the same, then the bug should have already been fixed in version 2.0.2. The next release of 1.10 (1.10.17), which is planned for tomorrow, will also have this issue fixed.

**Comment by mkudelya** [comment] 2017-02-24 15:39
1.10.17 version has been released. I am now closing this issue. Please, feel free to reopen it if you have any questions.

**Closed by mkudelya** 2017-02-24 15:39 UTC
Labels: bug

**Comment by martinvonwittich** [comment] 2017-11-03 12:05
I can reproduce this issue on OroCRM 2.4.2. The cause seems to be our non-standard Cyrus configuration with the setting `unixhierarchysep: yes`. From `man imapd.conf`:

```
       unixhierarchysep: 0
            Use the UNIX separator character  '/'  for  delimiting  levels  of
            mailbox  hierarchy.   The  default is to use the netnews separator
            character '.'.
```

I manually patched our `vendor/oro/platform/src/Oro/Bundle/ImapBundle/Mail/Storage/Folder.php` and ran `app/console cache:clear --env prod`, that resolved the issue for us:

``` diff
orocrm.iserv.eu /var/www/orocrm # diff -u ~/Folder.php ./vendor/oro/platform/src/Oro/Bundle/ImapBundle/Mail/Storage/Folder.php
--- /var/lib/iserv/remote-support/iserv-martin.von.wittich/Folder.php   2017-11-02 17:19:23.894759352 +0100
+++ ./vendor/oro/platform/src/Oro/Bundle/ImapBundle/Mail/Storage/Folder.php     2017-11-03 12:58:23.698315175 +0100
@@ -31,23 +31,27 @@

         'Drafts'           => FolderType::DRAFTS,
         'INBOX.Drafts'     => FolderType::DRAFTS,
+        'INBOX/Drafts'     => FolderType::DRAFTS,

         'Spam'             => FolderType::SPAM,
         'Junk'             => FolderType::SPAM,
         'Junk E-mail'      => FolderType::SPAM,
         'INBOX.Junk'       => FolderType::SPAM,
+        'INBOX/Junk'       => FolderType::SPAM,

         'Sent'             => FolderType::SENT,
         'SentBox'          => FolderType::SENT,
         'Sent Items'       => FolderType::SENT,
         'Sent Messages'    => FolderType::SENT,
         'INBOX.Sent'       => FolderType::SENT,
+        'INBOX/Sent'       => FolderType::SENT,

         'Trash'            => FolderType::TRASH,
         'Deleted'          => FolderType::TRASH,
         'Deleted Items'    => FolderType::TRASH,
         'Deleted Messages' => FolderType::TRASH,
-        'INBOX.Trash'      => FolderType::TRASH
+        'INBOX.Trash'      => FolderType::TRASH,
+        'INBOX/Trash'      => FolderType::TRASH
     ];

     /** @var string[] */
```
